export const countryWithFlagList = [
  {
    id: "0",
    sortname: "",
    value: "0",
    label: "SELECT COUNTRY",
  },
  {
    id: "231",
    sortValue: "US",
    value: "United States",
    label: "🇺🇸 United States",
    phoneCode: "1",
  },
  {
    id: "1",
    sortValue: "AF",
    value: "Afghanistan",
    label: "🇦🇫 Afghanistan",
    phoneCode: "93",
  },
  {
    id: "2",
    sortValue: "AL",
    value: "Albania",
    label: "🇦🇱 Albania",
    phoneCode: "355",
  },
  {
    id: "3",
    sortValue: "DZ",
    value: "Algeria",
    label: "🇩🇿 Algeria",
    phoneCode: "213",
  },
  {
    id: "4",
    sortValue: "AS",
    value: "American Samoa",
    label: "🇦🇸 American Samoa",
    phoneCode: "1684",
  },
  {
    id: "5",
    sortValue: "AD",
    value: "Andorra",
    label: "🇦🇩 Andorra",
    phoneCode: "376",
  },
  {
    id: "6",
    sortValue: "AO",
    value: "Angola",
    label: "🇦🇴 Angola",
    phoneCode: "244",
  },
  {
    id: "7",
    sortValue: "AI",
    value: "Anguilla",
    label: "🇦🇮 Anguilla",
    phoneCode: "1264",
  },
  {
    id: "8",
    sortValue: "AQ",
    value: "Antarctica",
    label: "🇦🇶 Antarctica",
    phoneCode: "0",
  },
  {
    id: "9",
    sortValue: "AG",
    value: "Antigua And Barbuda",
    label: "🇦🇬 Antigua And Barbuda",
    phoneCode: "1268",
  },
  {
    id: "10",
    sortValue: "AR",
    value: "Argentina",
    label: "🇦🇷 Argentina",
    phoneCode: "54",
  },
  {
    id: "11",
    sortValue: "AM",
    value: "Armenia",
    label: "🇦🇲 Armenia",
    phoneCode: "374",
  },
  {
    id: "12",
    sortValue: "AW",
    value: "Aruba",
    label: "🇦🇼 Aruba",
    phoneCode: "297",
  },
  {
    id: "13",
    sortValue: "AU",
    value: "Australia",
    label: "🇦🇺 Australia",
    phoneCode: "61",
  },
  {
    id: "14",
    sortValue: "AT",
    value: "Austria",
    label: "🇦🇹 Austria",
    phoneCode: "43",
  },
  {
    id: "15",
    sortValue: "AZ",
    value: "Azerbaijan",
    label: "🇦🇿 Azerbaijan",
    phoneCode: "994",
  },
  {
    id: "16",
    sortValue: "BS",
    value: "Bahamas",
    label: "🇧🇸 Bahamas",
    phoneCode: "1242",
  },
  {
    id: "17",
    sortValue: "BH",
    value: "Bahrain",
    label: "🇧🇭 Bahrain",
    phoneCode: "973",
  },
  {
    id: "21",
    sortValue: "BE",
    value: "Belgium",
    label: "🇧🇪 Belgium",
    phoneCode: "32",
  },
  {
    id: "22",
    sortValue: "BZ",
    value: "Belize",
    label: "🇧🇿 Belize",
    phoneCode: "501",
  },
  {
    id: "23",
    sortValue: "BJ",
    value: "Benin",
    label: "🇧🇯 Benin",
    phoneCode: "229",
  },
  {
    id: "24",
    sortValue: "BM",
    value: "Bermuda",
    label: "🇧🇲 Bermuda",
    phoneCode: "1441",
  },
  {
    id: "25",
    sortValue: "BT",
    value: "Bhutan",
    label: "🇧🇹 Bhutan",
    phoneCode: "975",
  },
  {
    id: "26",
    sortValue: "BO",
    value: "Bolivia",
    label: "🇧🇴 Bolivia",
    phoneCode: "591",
  },
  {
    id: "27",
    sortValue: "BA",
    value: "Bosnia and Herzegovina",
    label: "🇧🇦 Bosnia and Herzegovina",
    phoneCode: "387",
  },
  {
    id: "28",
    sortValue: "BW",
    value: "Botswana",
    label: "🇧🇼 Botswana",
    phoneCode: "267",
  },
  {
    id: "29",
    sortValue: "BV",
    value: "Bouvet Island",
    label: "🇧🇻 Bouvet Island",
    phoneCode: "0",
  },
  {
    id: "30",
    sortValue: "BR",
    value: "Brazil",
    label: "🇧🇷 Brazil",
    phoneCode: "55",
  },
  {
    id: "31",
    sortValue: "IO",
    value: "British Indian Ocean Territory",
    label: "🇮🇴 British Indian Ocean Territory",
    phoneCode: "246",
  },
  {
    id: "32",
    sortValue: "BN",
    value: "Brunei Darussalam",
    label: "🇧🇳 Brunei Darussalam",
    phoneCode: "673",
  },
  {
    id: "33",
    sortValue: "BG",
    value: "Bulgaria",
    label: "🇧🇬 Bulgaria",
    phoneCode: "359",
  },
  {
    id: "34",
    sortValue: "BF",
    value: "Burkina Faso",
    label: "🇧🇫 Burkina Faso",
    phoneCode: "226",
  },
  {
    id: "36",
    sortValue: "KH",
    value: "Cambodia",
    label: "🇰🇭 Cambodia",
    phoneCode: "855",
  },
  {
    id: "37",
    sortValue: "CM",
    value: "Cameroon",
    label: "🇨🇲 Cameroon",
    phoneCode: "237",
  },
  {
    id: "38",
    sortValue: "CA",
    value: "Canada",
    label: "🇨🇦 Canada",
    phoneCode: "1",
  },
  {
    id: "39",
    sortValue: "CV",
    value: "Cape Verde",
    label: "🇨🇻 Cape Verde",
    phoneCode: "238",
  },
  {
    id: "40",
    sortValue: "KY",
    value: "Cayman Islands",
    label: "🇰🇾 Cayman Islands",
    phoneCode: "1345",
  },
  {
    id: "42",
    sortValue: "TD",
    value: "Chad",
    label: "🇹🇩 Chad",
    phoneCode: "235",
  },
  {
    id: "43",
    sortValue: "CL",
    value: "Chile",
    label: "🇨🇱 Chile",
    phoneCode: "56",
  },
  {
    id: "44",
    sortValue: "CN",
    value: "China",
    label: "🇨🇳 China",
    phoneCode: "86",
  },
  {
    id: "45",
    sortValue: "CX",
    value: "Christmas Island",
    label: "🇨🇽 Christmas Island",
    phoneCode: "61",
  },
  {
    id: "46",
    sortValue: "CC",
    value: "Cocos (Keeling) Islands",
    label: "🇨🇨 Cocos (Keeling) Islands",
    phoneCode: "672",
  },
  {
    id: "47",
    sortValue: "CO",
    value: "Colombia",
    label: "🇨🇴 Colombia",
    phoneCode: "57",
  },
  {
    id: "48",
    sortValue: "KM",
    value: "Comoros",
    label: "🇰🇲 Comoros",
    phoneCode: "269",
  },
  {
    id: "51",
    sortValue: "CK",
    value: "Cook Islands",
    label: "🇨🇰 Cook Islands",
    phoneCode: "682",
  },
  {
    id: "52",
    sortValue: "CR",
    value: "Costa Rica",
    label: "🇨🇷 Costa Rica",
    phoneCode: "506",
  },
  {
    id: "53",
    sortValue: "CI",
    value: "Cote D''Ivoire (Ivory Coast)",
    label: "🇨🇮 Cote D''Ivoire (Ivory Coast)",
    phoneCode: "225",
  },
  {
    id: "54",
    sortValue: "HR",
    value: "Croatia (Hrvatska)",
    label: "🇭🇷 Croatia (Hrvatska)",
    phoneCode: "385",
  },
  {
    id: "56",
    sortValue: "CY",
    value: "Cyprus",
    label: "🇨🇾 Cyprus",
    phoneCode: "357",
  },
  {
    id: "57",
    sortValue: "CZ",
    value: "Czech Republic",
    label: "🇨🇿 Czech Republic",
    phoneCode: "420",
  },
  {
    id: "58",
    sortValue: "DK",
    value: "Denmark",
    label: "🇩🇰 Denmark",
    phoneCode: "45",
  },
  {
    id: "59",
    sortValue: "DJ",
    value: "Djibouti",
    label: "🇩🇯 Djibouti",
    phoneCode: "253",
  },
  {
    id: "60",
    sortValue: "DM",
    value: "Dominica",
    label: "🇩🇲 Dominica",
    phoneCode: "1767",
  },
  {
    id: "61",
    sortValue: "DO",
    value: "Dominican Republic",
    label: "🇩🇴 Dominican Republic",
    phoneCode: "1809",
  },
  {
    id: "62",
    sortValue: "TP",
    value: "East Timor",
    label: "🇹🇱 East Timor",
    phoneCode: "670",
  },
  {
    id: "63",
    sortValue: "EC",
    value: "Ecuador",
    label: "🇪🇨 Ecuador",
    phoneCode: "593",
  },
  {
    id: "64",
    sortValue: "EG",
    value: "Egypt",
    label: "🇪🇬 Egypt",
    phoneCode: "20",
  },
  {
    id: "65",
    sortValue: "SV",
    value: "El Salvador",
    label: "🇸🇻 El Salvador",
    phoneCode: "503",
  },
  {
    id: "66",
    sortValue: "GQ",
    value: "Equatorial Guinea",
    label: "🇬🇶 Equatorial Guinea",
    phoneCode: "240",
  },
  {
    id: "67",
    sortValue: "ER",
    value: "Eritrea",
    label: "🇪🇷 Eritrea",
    phoneCode: "291",
  },
  {
    id: "68",
    sortValue: "EE",
    value: "Estonia",
    label: "🇪🇪 Estonia",
    phoneCode: "372",
  },
  {
    id: "71",
    sortValue: "FK",
    value: "Falkland Islands",
    label: "🇫🇰 Falkland Islands",
    phoneCode: "500",
  },
  {
    id: "72",
    sortValue: "FO",
    value: "Faroe Islands",
    label: "🇫🇴 Faroe Islands",
    phoneCode: "298",
  },
  {
    id: "73",
    sortValue: "FJ",
    value: "Fiji Islands",
    label: "🇫🇯 Fiji Islands",
    phoneCode: "679",
  },
  {
    id: "74",
    sortValue: "FI",
    value: "Finland",
    label: "🇫🇮 Finland",
    phoneCode: "358",
  },
  {
    id: "75",
    sortValue: "FR",
    value: "France",
    label: "🇫🇷 France",
    phoneCode: "33",
  },
  {
    id: "76",
    sortValue: "GF",
    value: "French Guiana",
    label: "🇬🇫 French Guiana",
    phoneCode: "594",
  },
  {
    id: "77",
    sortValue: "PF",
    value: "French Polynesia",
    label: "🇵🇫 French Polynesia",
    phoneCode: "689",
  },
  {
    id: "78",
    sortValue: "TF",
    value: "French Southern Territories",
    label: "🇹🇫 French Southern Territories",
    phoneCode: "0",
  },
  {
    id: "79",
    sortValue: "GA",
    value: "Gabon",
    label: "🇬🇦 Gabon",
    phoneCode: "241",
  },
  {
    id: "80",
    sortValue: "GM",
    value: "Gambia The",
    label: "🇬🇲 Gambia The",
    phoneCode: "220",
  },
  {
    id: "81",
    sortValue: "GE",
    value: "Georgia",
    label: "🇬🇪 Georgia",
    phoneCode: "995",
  },
  {
    id: "82",
    sortValue: "DE",
    value: "Germany",
    label: "🇩🇪 Germany",
    phoneCode: "49",
  },
  {
    id: "83",
    sortValue: "GH",
    value: "Ghana",
    label: "🇬🇭 Ghana",
    phoneCode: "233",
  },
  {
    id: "84",
    sortValue: "GI",
    value: "Gibraltar",
    label: "🇬🇮 Gibraltar",
    phoneCode: "350",
  },
  {
    id: "85",
    sortValue: "GR",
    value: "Greece",
    label: "🇬🇷 Greece",
    phoneCode: "30",
  },
  {
    id: "86",
    sortValue: "GL",
    value: "Greenland",
    label: "🇬🇱 Greenland",
    phoneCode: "299",
  },
  {
    id: "87",
    sortValue: "GD",
    value: "Grenada",
    label: "🇬🇩 Grenada",
    phoneCode: "1473",
  },
  {
    id: "88",
    sortValue: "GP",
    value: "Guadeloupe",
    label: "🇬🇵 Guadeloupe",
    phoneCode: "590",
  },
  {
    id: "89",
    sortValue: "GU",
    value: "Guam",
    label: "🇬🇺 Guam",
    phoneCode: "1671",
  },
  {
    id: "90",
    sortValue: "GT",
    value: "Guatemala",
    label: "🇬🇹 Guatemala",
    phoneCode: "502",
  },
  {
    id: "92",
    sortValue: "GN",
    value: "Guinea",
    label: "🇬🇳 Guinea",
    phoneCode: "224",
  },
  {
    id: "93",
    sortValue: "GW",
    value: "Guinea-Bissau",
    label: "🇬🇼 Guinea-Bissau",
    phoneCode: "245",
  },
  {
    id: "94",
    sortValue: "GY",
    value: "Guyana",
    label: "🇬🇾 Guyana",
    phoneCode: "592",
  },
  {
    id: "95",
    sortValue: "HT",
    value: "Haiti",
    label: "🇭🇹 Haiti",
    phoneCode: "509",
  },
  {
    id: "96",
    sortValue: "HM",
    value: "Heard and McDonald Islands",
    label: "🇭🇲 Heard and McDonald Islands",
    phoneCode: "0",
  },
  {
    id: "97",
    sortValue: "HN",
    value: "Honduras",
    label: "🇭🇳 Honduras",
    phoneCode: "504",
  },
  {
    id: "98",
    sortValue: "HK",
    value: "Hong Kong S.A.R.",
    label: "🇭🇰 Hong Kong S.A.R.",
    phoneCode: "852",
  },
  {
    id: "99",
    sortValue: "HU",
    value: "Hungary",
    label: "🇭🇺 Hungary",
    phoneCode: "36",
  },
  {
    id: "100",
    sortValue: "IS",
    value: "Iceland",
    label: "🇮🇸 Iceland",
    phoneCode: "354",
  },
  {
    id: "101",
    sortValue: "IN",
    value: "India",
    label: "🇮🇳 India",
    phoneCode: "91",
  },
  {
    id: "102",
    sortValue: "ID",
    value: "Indonesia",
    label: "🇮🇩 Indonesia",
    phoneCode: "62",
  },
  {
    id: "105",
    sortValue: "IE",
    value: "Ireland",
    label: "🇮🇪 Ireland",
    phoneCode: "353",
  },
  {
    id: "106",
    sortValue: "IL",
    value: "Israel",
    label: "🇮🇱 Israel",
    phoneCode: "972",
  },
  {
    id: "107",
    sortValue: "IT",
    value: "Italy",
    label: "🇮🇹 Italy",
    phoneCode: "39",
  },
  {
    id: "108",
    sortValue: "JM",
    value: "Jamaica",
    label: "🇯🇲 Jamaica",
    phoneCode: "1876",
  },
  {
    id: "109",
    sortValue: "JP",
    value: "Japan",
    label: "🇯🇵 Japan",
    phoneCode: "81",
  },
  {
    id: "111",
    sortValue: "JO",
    value: "Jordan",
    label: "🇯🇴 Jordan",
    phoneCode: "962",
  },
  {
    id: "112",
    sortValue: "KZ",
    value: "Kazakhstan",
    label: "🇰🇿 Kazakhstan",
    phoneCode: "7",
  },
  {
    id: "113",
    sortValue: "KE",
    value: "Kenya",
    label: "🇰🇪 Kenya",
    phoneCode: "254",
  },
  {
    id: "114",
    sortValue: "KI",
    value: "Kiribati",
    label: "🇰🇮 Kiribati",
    phoneCode: "686",
  },
  {
    id: "115",
    sortValue: "KP",
    value: "Korea North",
    label: "🇰🇵 Korea North",
    phoneCode: "850",
  },
  {
    id: "116",
    sortValue: "KR",
    value: "Korea South",
    label: "🇰🇷 Korea South",
    phoneCode: "82",
  },
  {
    id: "117",
    sortValue: "KW",
    value: "Kuwait",
    label: "🇰🇼 Kuwait",
    phoneCode: "965",
  },
  {
    id: "118",
    sortValue: "KG",
    value: "Kyrgyzstan",
    label: "🇰🇬 Kyrgyzstan",
    phoneCode: "996",
  },
  {
    id: "119",
    sortValue: "LA",
    value: "Laos People's Democratic Republic",
    label: "🇱🇦 Laos People's Democratic Republic",
    phoneCode: "856",
  },
  {
    id: "120",
    sortValue: "LV",
    value: "Latvia",
    label: "🇱🇻 Latvia",
    phoneCode: "371",
  },
  {
    id: "122",
    sortValue: "LS",
    value: "Lesotho",
    label: "🇱🇸 Lesotho",
    phoneCode: "266",
  },
  {
    id: "125",
    sortValue: "LI",
    value: "Liechtenstein",
    label: "🇱🇮 Liechtenstein",
    phoneCode: "423",
  },
  {
    id: "126",
    sortValue: "LT",
    value: "Lithuania",
    label: "🇱🇹 Lithuania",
    phoneCode: "370",
  },
  {
    id: "127",
    sortValue: "LU",
    value: "Luxembourg",
    label: "🇱🇺 Luxembourg",
    phoneCode: "352",
  },
  {
    id: "128",
    sortValue: "MO",
    value: "Macau S.A.R.",
    label: "🇲🇴 Macau S.A.R.",
    phoneCode: "853",
  },
  {
    id: "129",
    sortValue: "MK",
    value: "Macedonia",
    label: "🇲🇰 Macedonia",
    phoneCode: "389",
  },
  {
    id: "130",
    sortValue: "MG",
    value: "Madagascar",
    label: "🇲🇬 Madagascar",
    phoneCode: "261",
  },
  {
    id: "131",
    sortValue: "MW",
    value: "Malawi",
    label: "🇲🇼 Malawi",
    phoneCode: "265",
  },
  {
    id: "132",
    sortValue: "MY",
    value: "Malaysia",
    label: "🇲🇾 Malaysia",
    phoneCode: "60",
  },
  {
    id: "133",
    sortValue: "MV",
    value: "Maldives",
    label: "🇲🇻 Maldives",
    phoneCode: "960",
  },
  {
    id: "134",
    sortValue: "ML",
    value: "Mali",
    label: "🇲🇱 Mali",
    phoneCode: "223",
  },
  {
    id: "135",
    sortValue: "MT",
    value: "Malta",
    label: "🇲🇹 Malta",
    phoneCode: "356",
  },
  {
    id: "136",
    sortValue: "IM",
    value: "Man (Isle of)",
    label: "🇮🇲 Man (Isle of)",
    phoneCode: "44",
  },
  {
    id: "137",
    sortValue: "MH",
    value: "Marshall Islands",
    label: "🇲🇭 Marshall Islands",
    phoneCode: "692",
  },
  {
    id: "138",
    sortValue: "MQ",
    value: "Martinique",
    label: "🇲🇶 Martinique",
    phoneCode: "596",
  },
  {
    id: "139",
    sortValue: "MR",
    value: "Mauritania",
    label: "🇲🇷 Mauritania",
    phoneCode: "222",
  },
  {
    id: "140",
    sortValue: "MU",
    value: "Mauritius",
    label: "🇲🇺 Mauritius",
    phoneCode: "230",
  },
  {
    id: "141",
    sortValue: "YT",
    value: "Mayotte",
    label: "🇾🇹 Mayotte",
    phoneCode: "269",
  },
  {
    id: "142",
    sortValue: "MX",
    value: "Mexico",
    label: "🇲🇽 Mexico",
    phoneCode: "52",
  },
  {
    id: "143",
    sortValue: "FM",
    value: "Micronesia",
    label: "🇫🇲 Micronesia",
    phoneCode: "691",
  },
  {
    id: "144",
    sortValue: "MD",
    value: "Moldova",
    label: "🇲🇩 Moldova",
    phoneCode: "373",
  },
  {
    id: "145",
    sortValue: "MC",
    value: "Monaco",
    label: "🇲🇨 Monaco",
    phoneCode: "377",
  },
  {
    id: "146",
    sortValue: "MN",
    value: "Mongolia",
    label: "🇲🇳 Mongolia",
    phoneCode: "976",
  },
  {
    id: "147",
    sortValue: "MS",
    value: "Montserrat",
    label: "🇲🇸 Montserrat",
    phoneCode: "1664",
  },
  {
    id: "148",
    sortValue: "MA",
    value: "Morocco",
    label: "🇲🇦 Morocco",
    phoneCode: "212",
  },
  {
    id: "149",
    sortValue: "MZ",
    value: "Mozambique",
    label: "🇲🇿 Mozambique",
    phoneCode: "258",
  },
  {
    id: "151",
    sortValue: "NA",
    value: "Namibia",
    label: "🇳🇦 Namibia",
    phoneCode: "264",
  },
  {
    id: "152",
    sortValue: "NR",
    value: "Nauru",
    label: "🇳🇷 Nauru",
    phoneCode: "674",
  },
  {
    id: "153",
    sortValue: "NP",
    value: "Nepal",
    label: "🇳🇵 Nepal",
    phoneCode: "977",
  },
  {
    id: "154",
    sortValue: "AN",
    value: "Netherlands Antilles",
    label: "🇧🇶 Netherlands Antilles",
    phoneCode: "599",
  },
  {
    id: "155",
    sortValue: "NL",
    value: "Netherlands The",
    label: "🇳🇱 Netherlands The",
    phoneCode: "31",
  },
  {
    id: "156",
    sortValue: "NC",
    value: "New Caledonia",
    label: "🇳🇨 New Caledonia",
    phoneCode: "687",
  },
  {
    id: "157",
    sortValue: "NZ",
    value: "New Zealand",
    label: "🇳🇿 New Zealand",
    phoneCode: "64",
  },
  {
    id: "158",
    sortValue: "NI",
    value: "Nicaragua",
    label: "🇳🇮 Nicaragua",
    phoneCode: "505",
  },
  {
    id: "159",
    sortValue: "NE",
    value: "Niger",
    label: "🇳🇪 Niger",
    phoneCode: "227",
  },
  {
    id: "160",
    sortValue: "NG",
    value: "Nigeria",
    label: "🇳🇬 Nigeria",
    phoneCode: "234",
  },
  {
    id: "161",
    sortValue: "NU",
    value: "Niue",
    label: "🇳🇺 Niue",
    phoneCode: "683",
  },
  {
    id: "162",
    sortValue: "NF",
    value: "Norfolk Island",
    label: "🇳🇫 Norfolk Island",
    phoneCode: "672",
  },
  {
    id: "163",
    sortValue: "MP",
    value: "Northern Mariana Islands",
    label: "🇲🇵 Northern Mariana Islands",
    phoneCode: "1670",
  },
  {
    id: "164",
    sortValue: "NO",
    value: "Norway",
    label: "🇳🇴 Norway",
    phoneCode: "47",
  },
  {
    id: "165",
    sortValue: "OM",
    value: "Oman",
    label: "🇴🇲 Oman",
    phoneCode: "968",
  },
  {
    id: "166",
    sortValue: "PK",
    value: "Pakistan",
    label: "🇵🇰 Pakistan",
    phoneCode: "92",
  },
  {
    id: "167",
    sortValue: "PW",
    value: "Palau",
    label: "🇵🇼 Palau",
    phoneCode: "680",
  },
  {
    id: "168",
    sortValue: "PS",
    value: "Palestinian Territory Occupied",
    label: "🇵🇸 Palestinian Territory Occupied",
    phoneCode: "970",
  },
  {
    id: "169",
    sortValue: "PA",
    value: "Panama",
    label: "🇵🇦 Panama",
    phoneCode: "507",
  },
  {
    id: "170",
    sortValue: "PG",
    value: "Papua new Guinea",
    label: "🇵🇬 Papua new Guinea",
    phoneCode: "675",
  },
  {
    id: "171",
    sortValue: "PY",
    value: "Paraguay",
    label: "🇵🇾 Paraguay",
    phoneCode: "595",
  },
  {
    id: "172",
    sortValue: "PE",
    value: "Peru",
    label: "🇵🇪 Peru",
    phoneCode: "51",
  },
  {
    id: "173",
    sortValue: "PH",
    value: "Philippines",
    label: "🇵🇭 Philippines",
    phoneCode: "63",
  },
  {
    id: "174",
    sortValue: "PN",
    value: "Pitcairn Island",
    label: "🇵🇳 Pitcairn Island",
    phoneCode: "0",
  },
  {
    id: "175",
    sortValue: "PL",
    value: "Poland",
    label: "🇵🇱 Poland",
    phoneCode: "48",
  },
  {
    id: "176",
    sortValue: "PT",
    value: "Portugal",
    label: "🇵🇹 Portugal",
    phoneCode: "351",
  },
  {
    id: "177",
    sortValue: "PR",
    value: "Puerto Rico",
    label: "🇵🇷 Puerto Rico",
    phoneCode: "1787",
  },
  {
    id: "178",
    sortValue: "QA",
    value: "Qatar",
    label: "🇶🇦 Qatar",
    phoneCode: "974",
  },
  {
    id: "179",
    sortValue: "RE",
    value: "Reunion",
    label: "🇷🇪 Reunion",
    phoneCode: "262",
  },
  {
    id: "180",
    sortValue: "RO",
    value: "Romania",
    label: "🇷🇴 Romania",
    phoneCode: "40",
  },
  {
    id: "181",
    sortValue: "RU",
    value: "Russia",
    label: "🇷🇺 Russia",
    phoneCode: "70",
  },
  {
    id: "183",
    sortValue: "SH",
    value: "Saint Helena",
    label: "🇸🇭 Saint Helena",
    phoneCode: "290",
  },
  {
    id: "184",
    sortValue: "KN",
    value: "Saint Kitts And Nevis",
    label: "🇰🇳 Saint Kitts And Nevis",
    phoneCode: "1869",
  },
  {
    id: "185",
    sortValue: "LC",
    value: "Saint Lucia",
    label: "🇱🇨 Saint Lucia",
    phoneCode: "1758",
  },
  {
    id: "186",
    sortValue: "PM",
    value: "Saint Pierre and Miquelon",
    label: "🇵🇲 Saint Pierre and Miquelon",
    phoneCode: "508",
  },
  {
    id: "187",
    sortValue: "VC",
    value: "Saint Vincent And The Grenadines",
    label: "🇻🇨 Saint Vincent And The Grenadines",
    phoneCode: "1784",
  },
  {
    id: "188",
    sortValue: "WS",
    value: "Samoa",
    label: "🇼🇸 Samoa",
    phoneCode: "684",
  },
  {
    id: "189",
    sortValue: "SM",
    value: "San Marino",
    label: "🇸🇲 San Marino",
    phoneCode: "378",
  },
  {
    id: "190",
    sortValue: "ST",
    value: "Sao Tome and Principe",
    label: "🇸🇹 Sao Tome and Principe",
    phoneCode: "239",
  },
  {
    id: "191",
    sortValue: "SA",
    value: "Saudi Arabia",
    label: "🇸🇦 Saudi Arabia",
    phoneCode: "966",
  },
  {
    id: "192",
    sortValue: "SN",
    value: "Senegal",
    label: "🇸🇳 Senegal",
    phoneCode: "221",
  },
  {
    id: "193",
    sortValue: "RS",
    value: "Serbia",
    label: "🇷🇸 Serbia",
    phoneCode: "381",
  },
  {
    id: "194",
    sortValue: "SC",
    value: "Seychelles",
    label: "🇸🇨 Seychelles",
    phoneCode: "248",
  },
  {
    id: "195",
    sortValue: "SL",
    value: "Sierra Leone",
    label: "🇸🇱 Sierra Leone",
    phoneCode: "232",
  },
  {
    id: "196",
    sortValue: "SG",
    value: "Singapore",
    label: "🇸🇬 Singapore",
    phoneCode: "65",
  },
  {
    id: "197",
    sortValue: "SK",
    value: "Slovakia",
    label: "🇸🇰 Slovakia",
    phoneCode: "421",
  },
  {
    id: "198",
    sortValue: "SI",
    value: "Slovenia",
    label: "🇸🇮 Slovenia",
    phoneCode: "386",
  },
  {
    id: "200",
    sortValue: "SB",
    value: "Solomon Islands",
    label: "🇸🇧 Solomon Islands",
    phoneCode: "677",
  },
  {
    id: "202",
    sortValue: "ZA",
    value: "South Africa",
    label: "🇿🇦 South Africa",
    phoneCode: "27",
  },
  {
    id: "203",
    sortValue: "GS",
    value: "South Georgia",
    label: "🇬🇸 South Georgia",
    phoneCode: "0",
  },
  {
    id: "204",
    sortValue: "SS",
    value: "South Sudan",
    label: "🇸🇸 South Sudan",
    phoneCode: "211",
  },
  {
    id: "205",
    sortValue: "ES",
    value: "Spain",
    label: "🇪🇸 Spain",
    phoneCode: "34",
  },
  {
    id: "206",
    sortValue: "LK",
    value: "Sri Lanka",
    label: "🇱🇰 Sri Lanka",
    phoneCode: "94",
  },
  {
    id: "208",
    sortValue: "SR",
    value: "Suriname",
    label: "🇸🇷 Suriname",
    phoneCode: "597",
  },
  {
    id: "209",
    sortValue: "SJ",
    value: "Svalbard And Jan Mayen Islands",
    label: "🇸🇯 Svalbard And Jan Mayen Islands",
    phoneCode: "47",
  },
  {
    id: "210",
    sortValue: "SZ",
    value: "Swaziland",
    label: "🇸🇿 Swaziland",
    phoneCode: "268",
  },
  {
    id: "211",
    sortValue: "SE",
    value: "Sweden",
    label: "🇸🇪 Sweden",
    phoneCode: "46",
  },
  {
    id: "212",
    sortValue: "CH",
    value: "Switzerland",
    label: "🇨🇭 Switzerland",
    phoneCode: "41",
  },
  {
    id: "214",
    sortValue: "TW",
    value: "Taiwan",
    label: "🇹🇼 Taiwan",
    phoneCode: "886",
  },
  {
    id: "215",
    sortValue: "TJ",
    value: "Tajikistan",
    label: "🇹🇯 Tajikistan",
    phoneCode: "992",
  },
  {
    id: "216",
    sortValue: "TZ",
    value: "Tanzania",
    label: "🇹🇿 Tanzania",
    phoneCode: "255",
  },
  {
    id: "217",
    sortValue: "TH",
    value: "Thailand",
    label: "🇹🇭 Thailand",
    phoneCode: "66",
  },
  {
    id: "218",
    sortValue: "TG",
    value: "Togo",
    label: "🇹🇬 Togo",
    phoneCode: "228",
  },
  {
    id: "219",
    sortValue: "TK",
    value: "Tokelau",
    label: "🇹🇰 Tokelau",
    phoneCode: "690",
  },
  {
    id: "220",
    sortValue: "TO",
    value: "Tonga",
    label: "🇹🇴 Tonga",
    phoneCode: "676",
  },
  {
    id: "221",
    sortValue: "TT",
    value: "Trinidad And Tobago",
    label: "🇹🇹 Trinidad And Tobago",
    phoneCode: "1868",
  },
  {
    id: "222",
    sortValue: "TN",
    value: "Tunisia",
    label: "🇹🇳 Tunisia",
    phoneCode: "216",
  },
  {
    id: "223",
    sortValue: "TR",
    value: "Turkey",
    label: "🇹🇷 Turkey",
    phoneCode: "90",
  },
  {
    id: "224",
    sortValue: "TM",
    value: "Turkmenistan",
    label: "🇹🇲 Turkmenistan",
    phoneCode: "7370",
  },
  {
    id: "225",
    sortValue: "TC",
    value: "Turks And Caicos Islands",
    label: "🇹🇨 Turks And Caicos Islands",
    phoneCode: "1649",
  },
  {
    id: "226",
    sortValue: "TV",
    value: "Tuvalu",
    label: "🇹🇻 Tuvalu",
    phoneCode: "688",
  },
  {
    id: "227",
    sortValue: "UG",
    value: "Uganda",
    label: "🇺🇬 Uganda",
    phoneCode: "256",
  },
  {
    id: "228",
    sortValue: "UA",
    value: "Ukraine",
    label: "🇺🇦 Ukraine",
    phoneCode: "380",
  },
  {
    id: "229",
    sortValue: "AE",
    value: "United Arab Emirates",
    label: "🇦🇪 United Arab Emirates",
    phoneCode: "971",
  },
  {
    id: "230",
    sortValue: "GB",
    value: "United Kingdom",
    label: "🇬🇧 United Kingdom",
    phoneCode: "44",
  },
  {
    id: "232",
    sortValue: "UM",
    value: "United States Minor Outlying Islands",
    label: "🇺🇲 United States Minor Outlying Islands",
    phoneCode: "1",
  },
  {
    id: "233",
    sortValue: "UY",
    value: "Uruguay",
    label: "🇺🇾 Uruguay",
    phoneCode: "598",
  },
  {
    id: "234",
    sortValue: "UZ",
    value: "Uzbekistan",
    label: "🇺🇿 Uzbekistan",
    phoneCode: "998",
  },
  {
    id: "235",
    sortValue: "VU",
    value: "Vanuatu",
    label: "🇻🇺 Vanuatu",
    phoneCode: "678",
  },
  {
    id: "236",
    sortValue: "VA",
    value: "Vatican City State (Holy See)",
    label: "🇻🇦 Vatican City State (Holy See)",
    phoneCode: "39",
  },
  {
    id: "237",
    sortname: "VE",
    value: "Venezuela",
    label: "🇻🇪 Venezuela",
    phoneCode: "58",
  },
  {
    id: "238",
    sortname: "VN",
    value: "Vietnam",
    label: "🇻🇳 Vietnam",
    phoneCode: "84",
  },
  {
    id: "239",
    sortValue: "VG",
    value: "Virgin Islands (British)",
    label: "🇻🇬 Virgin Islands (British)",
    phoneCode: "1284",
  },
  {
    id: "240",
    sortValue: "VI",
    value: "Virgin Islands (US)",
    label: "🇻🇮 Virgin Islands (US)",
    phoneCode: "1340",
  },
  {
    id: "241",
    sortValue: "WF",
    value: "Wallis And Futuna Islands",
    label: "🇼🇫 Wallis And Futuna Islands",
    phoneCode: "681",
  },
  {
    id: "242",
    sortValue: "EH",
    value: "Western Sahara",
    label: "🇪🇭 Western Sahara",
    phoneCode: "212",
  },
  {
    id: "245",
    sortValue: "ZM",
    value: "Zambia",
    label: "🇿🇲 Zambia",
    phoneCode: "260",
  },
  {
    id: "246",
    sortValue: "ME",
    value: "Montenegro",
    label: "🇲🇪 Montenegro",
    phoneCode: "382",
  },
  {
    id: "247",
    sortValue: "IM",
    value: "Isle of Man",
    label: "🇮🇲 Isle of Man",
    phoneCode: "44",
  },
  {
    id: "248",
    sortValue: "XK",
    value: "Kosovo",
    label: "🇽🇰 Kosovo",
    phoneCode: "383",
  },
  {
    id: "249",
    sortValue: "GG",
    value: "Bailiwick of Guernsey",
    label: "🇬🇬 Bailiwick of Guernsey",
    phoneCode: "44",
  },
  {
    id: "250",
    sortValue: "JE",
    value: "Bailiwick of Jersey",
    label: "🇯🇪 Bailiwick of Jersey",
    phoneCode: "44",
  },
  {
    id: "251",
    sortValue: "CW",
    value: "Curacao",
    label: "🇨🇼 Curacao",
    phoneCode: "599",
  },
];
