import { v4 as uuid } from "uuid";

export const worldsLanguageList = [
  { id: uuid(), value: "ab", code: "ab", name: "Abkhaz", nativeName: "аҧсуа" },
  { id: uuid(), value: "aa", code: "aa", name: "Afar", nativeName: "Afaraf" },
  { id: uuid(), value: "af", code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
  { id: uuid(), value: "ak", code: "ak", name: "Akan", nativeName: "Akan" },
  { id: uuid(), value: "sq", code: "sq", name: "Albanian", nativeName: "Shqip" },
  { id: uuid(), value: "am", code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { id: uuid(), value: "ar", code: "ar", name: "Arabic", nativeName: "العربية" },
  { id: uuid(), value: "an", code: "an", name: "Aragonese", nativeName: "Aragonés" },
  { id: uuid(), value: "hy", code: "hy", name: "Armenian", nativeName: "Հայերեն" },
  { id: uuid(), value: "as", code: "as", name: "Assamese", nativeName: "অসমীয়া" },
  { id: uuid(), value: "av", code: "av", name: "Avaric", nativeName: "авар мацӀ, магӀарул мацӀ" },
  { id: uuid(), value: "ae", code: "ae", name: "Avestan", nativeName: "avesta" },
  { id: uuid(), value: "ay", code: "ay", name: "Aymara", nativeName: "aymar aru" },
  { id: uuid(), value: "az", code: "az", name: "Azerbaijani", nativeName: "azərbaycan dili" },
  { id: uuid(), value: "bm", code: "bm", name: "Bambara", nativeName: "bamanankan" },
  { id: uuid(), value: "ba", code: "ba", name: "Bashkir", nativeName: "башҡорт теле" },
  { id: uuid(), value: "eu", code: "eu", name: "Basque", nativeName: "euskara, euskera" },
  { id: uuid(), value: "be", code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { id: uuid(), value: "bn", code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { id: uuid(), value: "bh", code: "bh", name: "Bihari", nativeName: "भोजपुरी" },
  { id: uuid(), value: "bi", code: "bi", name: "Bislama", nativeName: "Bislama" },
  { id: uuid(), value: "bs", code: "bs", name: "Bosnian", nativeName: "bosanski jezik" },
  { id: uuid(), value: "br", code: "br", name: "Breton", nativeName: "brezhoneg" },
  { id: uuid(), value: "bg", code: "bg", name: "Bulgarian", nativeName: "български език" },
  { id: uuid(), value: "my", code: "my", name: "Burmese", nativeName: "ဗမာစာ" },
  { id: uuid(), value: "ca", code: "ca", name: "Catalan; Valencian", nativeName: "Català" },
  { id: uuid(), value: "ch", code: "ch", name: "Chamorro", nativeName: "Chamoru" },
  { id: uuid(), value: "ce", code: "ce", name: "Chechen", nativeName: "нохчийн мотт" },
  { id: uuid(), value: "ny", code: "ny", name: "Chichewa; Chewa; Nyanja", nativeName: "chiCheŵa, chinyanja" },
  { id: uuid(), value: "zh", code: "zh", name: "Chinese", nativeName: "中文 (Zhōngwén), 汉语, 漢語" },
  { id: uuid(), value: "cv", code: "cv", name: "Chuvash", nativeName: "чӑваш чӗлхи" },
  { id: uuid(), value: "kw", code: "kw", name: "Cornish", nativeName: "Kernewek" },
  { id: uuid(), value: "co", code: "co", name: "Corsican", nativeName: "corsu, lingua corsa" },
  { id: uuid(), value: "cr", code: "cr", name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ" },
  { id: uuid(), value: "hr", code: "hr", name: "Croatian", nativeName: "hrvatski" },
  { id: uuid(), value: "cs", code: "cs", name: "Czech", nativeName: "česky, čeština" },
  { id: uuid(), value: "da", code: "da", name: "Danish", nativeName: "dansk" },
  { id: uuid(), value: "dv", code: "dv", name: "Divehi; Dhivehi; Maldivian;", nativeName: "ދިވެހި" },
  { id: uuid(), value: "nl", code: "nl", name: "Dutch", nativeName: "Nederlands, Vlaams" },
  { id: uuid(), value: "en", code: "en", name: "English", nativeName: "English" },
  { id: uuid(), value: "eo", code: "eo", name: "Esperanto", nativeName: "Esperanto" },
  { id: uuid(), value: "et", code: "et", name: "Estonian", nativeName: "eesti, eesti keel" },
  { id: uuid(), value: "ee", code: "ee", name: "Ewe", nativeName: "Eʋegbe" },
  { id: uuid(), value: "fo", code: "fo", name: "Faroese", nativeName: "føroyskt" },
  { id: uuid(), value: "fj", code: "fj", name: "Fijian", nativeName: "vosa Vakaviti" },
  { id: uuid(), value: "fi", code: "fi", name: "Finnish", nativeName: "suomi, suomen kieli" },
  { id: uuid(), value: "fr", code: "fr", name: "French", nativeName: "français, langue française" },
  { id: uuid(), value: "ff", code: "ff", name: "Fula; Fulah; Pulaar; Pular", nativeName: "Fulfulde, Pulaar, Pular" },
  { id: uuid(), value: "gl", code: "gl", name: "Galician", nativeName: "Galego" },
  { id: uuid(), value: "ka", code: "ka", name: "Georgian", nativeName: "ქართული" },
  { id: uuid(), value: "de", code: "de", name: "German", nativeName: "Deutsch" },
  { id: uuid(), value: "el", code: "el", name: "Greek, Modern", nativeName: "Ελληνικά" },
  { id: uuid(), value: "gn", code: "gn", name: "Guaraní", nativeName: "Avañeẽ" },
  { id: uuid(), value: "gu", code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { id: uuid(), value: "ht", code: "ht", name: "Haitian; Haitian Creole", nativeName: "Kreyòl ayisyen" },
  { id: uuid(), value: "ha", code: "ha", name: "Hausa", nativeName: "Hausa, هَوُسَ" },
  { id: uuid(), value: "he", code: "he", name: "Hebrew (modern)", nativeName: "עברית" },
  { id: uuid(), value: "hz", code: "hz", name: "Herero", nativeName: "Otjiherero" },
  { id: uuid(), value: "hi", code: "hi", name: "Hindi", nativeName: "हिन्दी, हिंदी" },
  { id: uuid(), value: "ho", code: "ho", name: "Hiri Motu", nativeName: "Hiri Motu" },
  { id: uuid(), value: "hu", code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { id: uuid(), value: "ia", code: "ia", name: "Interlingua", nativeName: "Interlingua" },
  { id: uuid(), value: "id", code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  {
    id: uuid(),
    value: "ie",
    code: "ie",
    name: "Interlingue",
    nativeName: "Originally called Occidental; then Interlingue after WWII",
  },
  { id: uuid(), value: "ga", code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { id: uuid(), value: "ig", code: "ig", name: "Igbo", nativeName: "Asụsụ Igbo" },
  { id: uuid(), value: "ik", code: "ik", name: "Inupiaq", nativeName: "Iñupiaq, Iñupiatun" },
  { id: uuid(), value: "io", code: "io", name: "Ido", nativeName: "Ido" },
  { id: uuid(), value: "is", code: "is", name: "Icelandic", nativeName: "Íslenska" },
  { id: uuid(), value: "it", code: "it", name: "Italian", nativeName: "Italiano" },
  { id: uuid(), value: "iu", code: "iu", name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ" },
  { id: uuid(), value: "ja", code: "ja", name: "Japanese", nativeName: "日本語 (にほんご／にっぽんご)" },
  { id: uuid(), value: "jv", code: "jv", name: "Javanese", nativeName: "basa Jawa" },
  {
    id: uuid(),
    value: "kl",
    code: "kl",
    name: "Kalaallisut, Greenlandic",
    nativeName: "kalaallisut, kalaallit oqaasii",
  },
  { id: uuid(), value: "kn", code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { id: uuid(), value: "kr", code: "kr", name: "Kanuri", nativeName: "Kanuri" },
  { id: uuid(), value: "ks", code: "ks", name: "Kashmiri", nativeName: "कश्मीरी, كشميري‎" },
  { id: uuid(), value: "kk", code: "kk", name: "Kazakh", nativeName: "Қазақ тілі" },
  { id: uuid(), value: "km", code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { id: uuid(), value: "ki", code: "ki", name: "Kikuyu, Gikuyu", nativeName: "Gĩkũyũ" },
  { id: uuid(), value: "rw", code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda" },
  { id: uuid(), value: "ky", code: "ky", name: "Kirghiz, Kyrgyz", nativeName: "кыргыз тили" },
  { id: uuid(), value: "kv", code: "kv", name: "Komi", nativeName: "коми кыв" },
  { id: uuid(), value: "kg", code: "kg", name: "Kongo", nativeName: "KiKongo" },
  { id: uuid(), value: "ko", code: "ko", name: "Korean", nativeName: "한국어 (韓國語), 조선말 (朝鮮語)" },
  { id: uuid(), value: "ku", code: "ku", name: "Kurdish", nativeName: "Kurdî, كوردی‎" },
  { id: uuid(), value: "kj", code: "kj", name: "Kwanyama, Kuanyama", nativeName: "Kuanyama" },
  { id: uuid(), value: "la", code: "la", name: "Latin", nativeName: "latine, lingua latina" },
  { id: uuid(), value: "lb", code: "lb", name: "Luxembourgish, Letzeburgesch", nativeName: "Lëtzebuergesch" },
  { id: uuid(), value: "lg", code: "lg", name: "Luganda", nativeName: "Luganda" },
  { id: uuid(), value: "li", code: "li", name: "Limburgish, Limburgan, Limburger", nativeName: "Limburgs" },
  { id: uuid(), value: "ln", code: "ln", name: "Lingala", nativeName: "Lingála" },
  { id: uuid(), value: "lo", code: "lo", name: "Lao", nativeName: "ພາສາລາວ" },
  { id: uuid(), value: "lt", code: "lt", name: "Lithuanian", nativeName: "lietuvių kalba" },
  { id: uuid(), value: "lu", code: "lu", name: "Luba-Katanga", nativeName: "" },
  { id: uuid(), value: "lv", code: "lv", name: "Latvian", nativeName: "latviešu valoda" },
  { id: uuid(), value: "gv", code: "gv", name: "Manx", nativeName: "Gaelg, Gailck" },
  { id: uuid(), value: "mk", code: "mk", name: "Macedonian", nativeName: "македонски јазик" },
  { id: uuid(), value: "mg", code: "mg", name: "Malagasy", nativeName: "Malagasy fiteny" },
  { id: uuid(), value: "ms", code: "ms", name: "Malay", nativeName: "bahasa Melayu, بهاس ملايو‎" },
  { id: uuid(), value: "ml", code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { id: uuid(), value: "mt", code: "mt", name: "Maltese", nativeName: "Malti" },
  { id: uuid(), value: "mi", code: "mi", name: "Māori", nativeName: "te reo Māori" },
  { id: uuid(), value: "mr", code: "mr", name: "Marathi (Marāṭhī)", nativeName: "मराठी" },
  { id: uuid(), value: "mh", code: "mh", name: "Marshallese", nativeName: "Kajin M̧ajeļ" },
  { id: uuid(), value: "mn", code: "mn", name: "Mongolian", nativeName: "монгол" },
  { id: uuid(), value: "na", code: "na", name: "Nauru", nativeName: "Ekakairũ Naoero" },
  { id: uuid(), value: "nv", code: "nv", name: "Navajo, Navaho", nativeName: "Diné bizaad, Dinékʼehǰí" },
  { id: uuid(), value: "nb", code: "nb", name: "Norwegian Bokmål", nativeName: "Norsk bokmål" },
  { id: uuid(), value: "nd", code: "nd", name: "North Ndebele", nativeName: "isiNdebele" },
  { id: uuid(), value: "ne", code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { id: uuid(), value: "ng", code: "ng", name: "Ndonga", nativeName: "Owambo" },
  { id: uuid(), value: "nn", code: "nn", name: "Norwegian Nynorsk", nativeName: "Norsk nynorsk" },
  { id: uuid(), value: "no", code: "no", name: "Norwegian", nativeName: "Norsk" },
  { id: uuid(), value: "ii", code: "ii", name: "Nuosu", nativeName: "ꆈꌠ꒿ Nuosuhxop" },
  { id: uuid(), value: "nr", code: "nr", name: "South Ndebele", nativeName: "isiNdebele" },
  { id: uuid(), value: "oc", code: "oc", name: "Occitan", nativeName: "Occitan" },
  { id: uuid(), value: "oj", code: "oj", name: "Ojibwe, Ojibwa", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
  {
    id: uuid(),
    value: "cu",
    code: "cu",
    name: "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
    nativeName: "ѩзыкъ словѣньскъ",
  },
  { id: uuid(), value: "om", code: "om", name: "Oromo", nativeName: "Afaan Oromoo" },
  { id: uuid(), value: "or", code: "or", name: "Oriya", nativeName: "ଓଡ଼ିଆ" },
  { id: uuid(), value: "os", code: "os", name: "Ossetian, Ossetic", nativeName: "ирон æвзаг" },
  { id: uuid(), value: "pa", code: "pa", name: "Panjabi, Punjabi", nativeName: "ਪੰਜਾਬੀ, پنجابی‎" },
  { id: uuid(), value: "pi", code: "pi", name: "Pāli", nativeName: "पाऴि" },
  { id: uuid(), value: "fa", code: "fa", name: "Persian", nativeName: "فارسی" },
  { id: uuid(), value: "pl", code: "pl", name: "Polish", nativeName: "polski" },
  { id: uuid(), value: "ps", code: "ps", name: "Pashto, Pushto", nativeName: "پښتو" },
  { id: uuid(), value: "pt", code: "pt", name: "Portuguese", nativeName: "Português" },
  { id: uuid(), value: "qu", code: "qu", name: "Quechua", nativeName: "Runa Simi, Kichwa" },
  { id: uuid(), value: "rm", code: "rm", name: "Romansh", nativeName: "rumantsch grischun" },
  { id: uuid(), value: "rn", code: "rn", name: "Kirundi", nativeName: "kiRundi" },
  { id: uuid(), value: "ro", code: "ro", name: "Romanian, Moldavian, Moldovan", nativeName: "română" },
  { id: uuid(), value: "ru", code: "ru", name: "Russian", nativeName: "русский язык" },
  { id: uuid(), value: "sa", code: "sa", name: "Sanskrit (Saṁskṛta)", nativeName: "संस्कृतम्" },
  { id: uuid(), value: "sc", code: "sc", name: "Sardinian", nativeName: "sardu" },
  { id: uuid(), value: "sd", code: "sd", name: "Sindhi", nativeName: "सिन्धी, سنڌي، سندھی‎" },
  { id: uuid(), value: "se", code: "se", name: "Northern Sami", nativeName: "Davvisámegiella" },
  { id: uuid(), value: "sm", code: "sm", name: "Samoan", nativeName: "gagana faa Samoa" },
  { id: uuid(), value: "sg", code: "sg", name: "Sango", nativeName: "yângâ tî sängö" },
  { id: uuid(), value: "sr", code: "sr", name: "Serbian", nativeName: "српски језик" },
  { id: uuid(), value: "gd", code: "gd", name: "Scottish Gaelic; Gaelic", nativeName: "Gàidhlig" },
  { id: uuid(), value: "sn", code: "sn", name: "Shona", nativeName: "chiShona" },
  { id: uuid(), value: "si", code: "si", name: "Sinhala, Sinhalese", nativeName: "සිංහල" },
  { id: uuid(), value: "sk", code: "sk", name: "Slovak", nativeName: "slovenčina" },
  { id: uuid(), value: "sl", code: "sl", name: "Slovene", nativeName: "slovenščina" },
  { id: uuid(), value: "so", code: "so", name: "Somali", nativeName: "Soomaaliga, af Soomaali" },
  { id: uuid(), value: "st", code: "st", name: "Southern Sotho", nativeName: "Sesotho" },
  { id: uuid(), value: "es", code: "es", name: "Spanish; Castilian", nativeName: "español, castellano" },
  { id: uuid(), value: "su", code: "su", name: "Sundanese", nativeName: "Basa Sunda" },
  { id: uuid(), value: "sw", code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { id: uuid(), value: "ss", code: "ss", name: "Swati", nativeName: "SiSwati" },
  { id: uuid(), value: "sv", code: "sv", name: "Swedish", nativeName: "svenska" },
  { id: uuid(), value: "ta", code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { id: uuid(), value: "te", code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { id: uuid(), value: "tg", code: "tg", name: "Tajik", nativeName: "тоҷикӣ, toğikī, تاجیکی‎" },
  { id: uuid(), value: "th", code: "th", name: "Thai", nativeName: "ไทย" },
  { id: uuid(), value: "ti", code: "ti", name: "Tigrinya", nativeName: "ትግርኛ" },
  { id: uuid(), value: "bo", code: "bo", name: "Tibetan Standard, Tibetan, Central", nativeName: "བོད་ཡིག" },
  { id: uuid(), value: "tk", code: "tk", name: "Turkmen", nativeName: "Türkmen, Түркмен" },
  { id: uuid(), value: "tl", code: "tl", name: "Tagalog", nativeName: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔" },
  { id: uuid(), value: "tn", code: "tn", name: "Tswana", nativeName: "Setswana" },
  { id: uuid(), value: "to", code: "to", name: "Tonga (Tonga Islands)", nativeName: "faka Tonga" },
  { id: uuid(), value: "tr", code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { id: uuid(), value: "ts", code: "ts", name: "Tsonga", nativeName: "Xitsonga" },
  { id: uuid(), value: "tt", code: "tt", name: "Tatar", nativeName: "татарча, tatarça, تاتارچا‎" },
  { id: uuid(), value: "tw", code: "tw", name: "Twi", nativeName: "Twi" },
  { id: uuid(), value: "ty", code: "ty", name: "Tahitian", nativeName: "Reo Tahiti" },
  { id: uuid(), value: "ug", code: "ug", name: "Uighur, Uyghur", nativeName: "Uyƣurqə, ئۇيغۇرچە‎" },
  { id: uuid(), value: "uk", code: "uk", name: "Ukrainian", nativeName: "українська" },
  { id: uuid(), value: "ur", code: "ur", name: "Urdu", nativeName: "اردو" },
  { id: uuid(), value: "uz", code: "uz", name: "Uzbek", nativeName: "zbek, Ўзбек, أۇزبېك‎" },
  { id: uuid(), value: "ve", code: "ve", name: "Venda", nativeName: "Tshivenḓa" },
  { id: uuid(), value: "vi", code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { id: uuid(), value: "vo", code: "vo", name: "Volapük", nativeName: "Volapük" },
  { id: uuid(), value: "wa", code: "wa", name: "Walloon", nativeName: "Walon" },
  { id: uuid(), value: "cy", code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { id: uuid(), value: "wo", code: "wo", name: "Wolof", nativeName: "Wollof" },
  { id: uuid(), value: "fy", code: "fy", name: "Western Frisian", nativeName: "Frysk" },
  { id: uuid(), value: "xh", code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { id: uuid(), value: "yi", code: "yi", name: "Yiddish", nativeName: "ייִדיש" },
  { id: uuid(), value: "yo", code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { id: uuid(), value: "za", code: "za", name: "Zhuang, Chuang", nativeName: "Saɯ cueŋƅ, Saw cuengh" },
];
