import { v4 as uuid } from "uuid";

import appConfig from "@/config";
import i18n from "@/i18n";
import { countryWithFlagList, worldsLanguageList } from "@/lib/auth/constants";

import { userRatedSvg, userRisingTalentSvg, userTopRatedSvg } from "./allSvgs";
import { getRedirectUrl } from "./config";

export const AUTH_COOKIE_EXPIRATION_TIME_IN_DAYS = 15;
export const PAGINATION_DEFAULT_LIMIT = 10; // Freelancers list, jobs list

export const commonConstant = {
  socket: null,
};

export const localStorageKeys = {
  authKey: "token",
  authAccountType: "accountType",
  userEmail: "user-email",
};

export const errorString = {
  catchError: "SOMETHING_WENT_WRONG",
  authError: "INVALID_AUTH_CRED",
  userIsNotLoggedIn: "USER_IS_NOT_LOGGED_IN",
  freelancerNotFound: "FREELANCE_PROFILE_NOT_FOUND",
  jobDetailNotFound: "JOB_DETAIL_NOT_FOUND",
  submitProposalConnectsNotFound: "SUBMIT_PROPOSAL_CONNECTS_NOT_FOUND",
  contractDetailNotFound: "CONTRACT_DETAIL_NOT_FOUND",
};

export const staticImagesUrl = {
  siteLogo: "",
};
export const keywords = {
  landingPage: "",
  contact: "Helius Contact,Helius Contact Us,Contact,Contact Us",
};

export const seoConfig = {
  additionalLinkTags: [
    {
      rel: "icon",
      href: `${appConfig.LIVE_URL}/favicon.ico`,
    },
    {
      rel: "icon",
      href: `${appConfig.LIVE_URL}/icon/favicon-32x32.png`,
      size: "32x32",
    },
    {
      rel: "icon",
      href: `${appConfig.LIVE_URL}/icon/favicon-16x16.png`,
      sizes: "16x16",
    },
    {
      rel: "apple-touch-icon",
      href: `${appConfig.LIVE_URL}/icon/apple-touch-icon.png`,
    },
    {
      rel: "mask-icon",
      href: `${appConfig.LIVE_URL}/icon/safari-pinned-tab.svg`,
      color: "#5bbad5",
    },
    {
      name: "msapplication-TileColor",
      content: "#da532c",
    },
    {
      name: "theme-color",
      content: "#ffffff",
    },
    {
      rel: "manifest",
      href: `${appConfig.LIVE_URL}/icon/site.webmanifest`,
    },
  ],
  login: {
    title: `Login`,
    titleTemplateAvail: true,
    canonical: getRedirectUrl("/account-security/login"),
    h1: "Login to Helius",
    desc: `Login with Helius`,
  },
  dashboard: {
    title: `Dashboard`,
    titleTemplateAvail: true,
    canonical: getRedirectUrl("/account-security/login"),
    h1: "Dashboard",
    desc: `Dashboard`,
  },
  loginWithLocalization: {
    title: `${i18n.t(`loginScreen.login`)}`,
    titleTemplateAvail: true,
    canonical: getRedirectUrl("/account-security/login"),
    h1: i18n.t(`loginScreen.login`),
    desc: `Login with ${i18n.t(`app_title`)}`,
  },
};

export const FreelancerSidebarFilterOptionsList = [
  {
    id: uuid(),
    title: "Talent Quality",
    options: [
      { id: uuid(), label: "Top Rated Plus", value: "Top Rated Plus", isIcon: true, icon: userRatedSvg },
      { id: uuid(), label: "Top Rated", value: "Top Rated", isIcon: true, icon: userTopRatedSvg },
      { id: uuid(), label: "Rising Talent", value: "Rising Talent", isIcon: true, icon: userRisingTalentSvg },
    ],
    isCheckbox: true,
    isRadio: false,
    isDropDown: false,
    dropdownOptions: null,
    isOptCollapsable: true,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "talentQuality",
  },
  {
    id: uuid(),
    title: "Category",
    options: [
      { id: uuid(), label: "Sales & Marketing", value: "salesAndMarketing", isIcon: false, icon: "" },
      { id: uuid(), label: "digital & Marketing", value: "salesAndMarketing", isIcon: false, icon: "" },
    ],
    isCheckbox: false,
    isRadio: false,
    isDropDown: false,
    dropdownOptions: null,
    isOptCollapsable: true,
    selectedOptions: [],
    isList: true,
    selectedValue: null,
    key: "category",
  },
  {
    id: uuid(),
    title: "Subcategory",
    options: [
      {
        id: uuid(),
        label: "Marketing, PR & Brand Strategy",
        value: "marketing,PR,And,BrandStrategy",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "digital, PR & Brand Strategy",
        value: "digital,PR,And,BrandStrategy",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: false,
    isRadio: false,
    isDropDown: false,
    isOptCollapsable: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: true,
    selectedValue: null,
    key: "subCategory",
  },
  {
    id: uuid(),
    title: "Specialties",
    options: [
      {
        id: uuid(),
        label: "Marketing Strategy",
        value: "marketingStrategy",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "test Strategy",
        value: "marketingStrategy",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: false,
    isRadio: false,
    isDropDown: false,
    dropdownOptions: null,
    selectedOptions: [],
    isOptCollapsable: true,
    isList: true,
    selectedValue: null,
    key: "specialities",
  },
  {
    id: uuid(),
    title: "Marketing Strategy Type",
    options: [
      {
        id: uuid(),
        label: "Influencer Marketing",
        value: "influencerMarketing",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Content Marketing",
        value: "contentMarketing",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Direct Marketing",
        value: "directMarketing",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Email Marketing",
        value: "emailMarketing",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    isOptCollapsable: false,
    dropdownOptions: null,
    selectedOptions: [],
    isList: true,
    selectedValue: null,
    key: "skills",
  },
  {
    id: uuid(),
    title: "Location",
    options: [],
    isCheckbox: true,
    isSearchable: true,
    isDropDown: true,
    isRadio: false,
    dropdownOptions: countryWithFlagList,
    selectedOptions: [],
    isOptCollapsable: true,
    isList: false,
    selectedValue: null,
    key: "location",
  },
  {
    id: uuid(),
    title: "Freelancer type",
    options: [
      {
        id: uuid(),
        label: "Freelancer & Agency",
        value: "freelancerAndAgency",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Freelancer",
        value: "freelancer",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Agency",
        value: "agency",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: false,
    isSearchable: false,
    isDropDown: false,
    isOptCollapsable: true,
    isRadio: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "freelancerType",
  },
  {
    id: uuid(),
    title: "Other Languages",
    options: [],
    isCheckbox: true,
    isSearchable: true,
    isDropDown: true,
    isRadio: false,
    dropdownOptions: worldsLanguageList,
    selectedOptions: [],
    isList: false,
    isOptCollapsable: true,
    selectedValue: null,
    key: "otherLanguages",
  },
  {
    id: uuid(),
    title: "Job success",
    options: [
      {
        id: uuid(),
        label: "Any Job Success",
        value: "Any Job Success",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "80% & up",
        value: 80,
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "90% & up",
        value: 90,
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: false,
    isSearchable: false,
    isDropDown: false,
    isOptCollapsable: true,
    isRadio: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "jobSuccess",
  },
  {
    id: uuid(),
    title: "Earned Amount",
    options: [
      {
        id: uuid(),
        label: "$0 to $1000 earned",
        value: "0-1000",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$1k+   earned",
        value: "1000-",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$2k+   earned",
        value: "2000-",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$5k and below",
        value: "0-5000",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$10k  and below",
        value: "0-10000",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    isOptCollapsable: true,
    selectedValue: null,
    key: "earnedAmount",
  },
  {
    id: uuid(),
    title: "Hours Billed",
    options: [
      {
        id: uuid(),
        label: "0 to 10 hour billed",
        value: "0-10",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "10+ hour billed",
        value: "10-",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "100+ hours billed",
        value: "100-",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "1000+  hours billed",
        value: "1000-",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    isOptCollapsable: true,
    key: "hoursBilled",
  },
  {
    id: uuid(),
    title: "English Proficiency",
    options: [
      {
        id: uuid(),
        label: "Any",
        value: "Any",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Conversational",
        value: "conversational",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Fluent",
        value: "fluent",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Bilingual",
        value: "bilingual",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: false,
    isSearchable: false,
    isDropDown: false,
    isOptCollapsable: true,
    isRadio: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "englishProficiency",
  },
  {
    id: uuid(),
    title: "Hourly rates",
    options: [
      {
        id: uuid(),
        label: "Any Hour Rates",
        value: "Any Hour Rates",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$10 and below",
        value: "0-10",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$10-$30",
        value: "10-30",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$30-$60",
        value: "30-60",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "$60 & Above",
        value: "60+",
        isIcon: false,
        icon: "",
      },
      // {
      //   id: uuid(),
      //   label: "No Earning Yet",
      //   value: "noEarningYet",
      //   isIcon: false,
      //   icon: "",
      // },
    ],
    isCheckbox: false,
    isSearchable: false,
    isDropDown: false,
    isOptCollapsable: true,
    isRadio: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "hourlyRates",
  },
];
export const JobPostSidebarFilterOptionsList = [
  {
    id: uuid(),
    title: "Category",
    options: [
      {
        id: uuid(),
        label: "Accounting & Consulting",
        value: "Accounting & Consulting",
        subItem: [
          { id: uuid(), label: "Life Coaching", value: "Life Coaching" },
          { id: uuid(), label: "Coaching", value: "Coaching" },
          { id: uuid(), label: "Bookkeeping", value: "Bookkeeping" },
        ],
        isIcon: false,

        icon: "",
      },
      {
        id: uuid(),
        label: "Admin Support",
        value: "Admin Support",
        subItem: [
          { id: uuid(), label: "Instructional Design", value: "Instructional Design" },
          { id: uuid(), label: "HR Administration", value: "HR Administration" },
          { id: uuid(), label: "Network Security", value: "Network Security" },
        ],
        isIcon: false,

        icon: "",
      },
      {
        id: uuid(),
        label: "Bookkeeping",
        value: "Bookkeeping",
        subItem: [
          { id: uuid(), label: "Training & Development", value: "Training & Development" },
          { id: uuid(), label: "Recruiting", value: "Recruiting" },
          { id: uuid(), label: "Talent Sourcing", value: "Talent Sourcing" },
          { id: uuid(), label: "Database Administration", value: "Database Administration" },
          { id: uuid(), label: "Accounting", value: "Accounting" },
          { id: uuid(), label: "Consulting", value: "Consulting" },
        ],
        isIcon: false,

        icon: "",
      },
    ],
    isCheckboxWithSelectOption: true,
    isMultipleCheckbox: false,
    dropdownOptions: null,
    isSearchable: true,
    isCheckbox: false,
    isRadio: false,
    isDropDown: false,
    isOptCollapsable: false,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "subCategory",
  },

  {
    id: uuid(),
    title: "Experience Level",
    options: [
      {
        id: uuid(),
        label: "Entry Level-$ ",
        value: "Entry",
        match: "entry",
        isIcon: false,

        icon: "",
      },
      {
        id: uuid(),
        label: "Intermediate-$$ ",
        value: "Intermediate",
        match: "intermediate",
        isIcon: false,

        icon: "",
      },
      {
        id: uuid(),
        label: "Expert - $$$ ",
        value: "Expert",
        match: "expert",
        isIcon: false,

        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    isOptCollapsable: true,
    isMultipleCheckbox: false,
    isCheckboxWithSelectOption: false,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "experience",
  },

  {
    id: uuid(),
    title: "Job Type",
    options: [
      {
        id: uuid(),
        label: "Hourly ",
        value: "hourlyRate",
        isIcon: false,
        icon: "",
        optionList: [
          {
            id: uuid(),
            isIcon: false,
            isInput: true,
            label: "Hourly Rate",
            value: "hourlyRate",
            icon: "",
            inputOptionsList: [
              {
                id: uuid(),
                label: "$ min",
                value: "min",
                isIcon: false,
                isInput: true,
                icon: "",
              },
              {
                id: uuid(),
                label: "$ max",
                value: "max",
                isIcon: false,
                isInput: true,
                icon: "",
              },
            ],
          },
        ],
      },
      {
        id: uuid(),
        label: "Fixed Price ",
        value: "fixedRate",
        isIcon: false,
        icon: "",
        optionList: [
          {
            id: uuid(),
            label: "Less than $100 ",
            value: "Less than $100",
            match: "fixed100",
            isIcon: false,
            isInput: false,
            icon: "",
          },
          {
            id: uuid(),
            label: "$100 - $500 ",
            value: "$100 - $500",
            match: "fixed500",
            isIcon: false,
            isInput: false,
            icon: "",
          },
          {
            id: uuid(),
            label: "$500 - $1k ",
            value: "$500 - $1k",
            match: "fixed1000",
            isIcon: false,
            isInput: false,
            icon: "",
          },
          {
            id: uuid(),
            label: "$1k - $5k ",
            value: "$1k - $5k",
            match: "fixed5000",
            isIcon: false,
            isInput: false,
            icon: "",
          },
          {
            id: uuid(),
            label: "$5k+ ",
            value: "$5k+",
            match: "fixedgt5000",
            isIcon: false,
            isInput: false,
            icon: "",
          },
          {
            id: uuid(),
            isIcon: false,
            isInput: true,
            label: "Fixed Rate",
            value: "fixedAmount",
            icon: "",
            inputOptionsList: [
              {
                id: uuid(),
                label: "$ min",
                value: "min",
                isIcon: false,
                isInput: true,
                icon: "",
              },
              {
                id: uuid(),
                label: "$ max",
                value: "max",
                isIcon: false,
                isInput: true,
                icon: "",
              },
            ],
          },
        ],
      },
    ],
    isCheckbox: false,
    isMultipleCheckbox: true,
    isCheckboxWithSelectOption: false,
    isDropDown: false,
    isRadio: false,
    isOptCollapsable: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "paymentType",
  },
  {
    id: uuid(),
    title: "Number of Proposals",
    options: [
      {
        id: uuid(),
        label: "Less than 5 ",
        value: "0-5",
        match: "proposal05",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "5 to 10 ",
        value: "5-10",
        match: "proposal510",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "10 to 15 ",
        value: "10-15",
        match: "proposal1015",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "15 to 20 ",
        value: "15-20",
        match: "proposal1520",
        isIcon: false,
        icon: "",
      },

      {
        id: uuid(),
        label: "20 to 50 ",
        value: "20-50",
        match: "proposal2050",
        isIcon: false,
        isInput: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    isOptCollapsable: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "proposal",
  },
  {
    id: uuid(),
    title: "Client Info",
    options: [
      {
        id: uuid(),
        label: "My previous clients",
        value: "My previous clients",
        match: "previousClient",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "Payment verified",
        value: "Payment verified",
        match: "paymentVerified",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    isOptCollapsable: true,
    isCheckboxWithSelectOption: false,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "paymentVerified",
  },
  // TODO : We need to work on this
  {
    id: uuid(),
    title: "Client History",
    options: [
      {
        id: uuid(),
        label: "No hires ",
        value: "No hires",
        match: "lt1",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "1 to 9 hires ",
        value: " 1 to 9 hires",
        match: "bt110",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "10+ hires ",
        value: "10+ hires",
        match: "gt10",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    isOptCollapsable: true,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "hired",
  },
  {
    id: uuid(),
    title: "Project Scope",
    options: [
      {
        id: uuid(),
        label: "Less than 1 month",
        value: "Less than 1 month",
        match: "scope1",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "1 to 3 months",
        value: "1 to 3 months",
        match: "scope13",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "3 to 6 months",
        value: "3 to 6 months",
        match: "scope36",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "More than 6 months",
        value: "More than 6 months",
        match: "scope6",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: false,
    isDropDown: false,
    isRadio: true,
    isOptCollapsable: true,
    isCheckboxWithSelectOption: false,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "duration",
  },
  {
    id: uuid(),
    title: "Hours Per Week",
    options: [
      {
        id: uuid(),
        label: "Less than 30 hrs/week",
        value: "Less than 30 hrs/week",
        match: "lt30",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "More than 30 hrs/week",
        value: "More than 30 hrs/week",
        match: "gt30",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isDropDown: false,
    isRadio: false,
    isOptCollapsable: true,
    isCheckboxWithSelectOption: false,
    dropdownOptions: null,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "hoursPerWeek",
  },
  {
    id: uuid(),
    title: "Client Location",
    options: [],
    isCheckbox: true,
    isSearchable: true,
    isDropDown: true,
    isRadio: false,
    isCheckboxWithSelectOption: false,
    dropdownOptions: countryWithFlagList,
    isOptCollapsable: true,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "location",
  },
  // TODO : We need to work on this
  // {
  //   id: uuid(),
  //   title: "Client time zones",
  //   options: [],
  //   isCheckbox: true,
  //   isSearchable: true,
  //   isDropDown: true,
  //   isRadio: false,
  //   dropdownOptions: countryWithFlagList,
  //   isCheckboxWithSelectOption: false,
  //   isOptCollapsable: true,
  //   selectedOptions: [],
  //   isList: false,
  //   selectedValue: null,
  //   key: "Client time zones",
  // },

  {
    id: uuid(),
    title: "Connects Needed",
    options: [
      {
        id: uuid(),
        label: "2 or less Connects ",
        value: "2 or less Connects",
        match: "connect12",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "4 Connects ",
        value: "4 Connects",
        match: "connect34",
        isIcon: false,
        icon: "",
      },
      {
        id: uuid(),
        label: "6 Connects ",
        value: "6 Connects",
        match: "connect56",
        isIcon: false,
        icon: "",
      },
    ],
    isCheckbox: true,
    isSearchable: false,
    isDropDown: false,
    isRadio: false,
    isCheckboxWithSelectOption: false,
    dropdownOptions: null,
    isOptCollapsable: true,
    selectedOptions: [],
    isList: false,
    selectedValue: null,
    key: "connects",
  },
];

// client side my jobs page options start
export const openOptionsList = [
  {
    id: uuid(),
    title: "editDraft",
    label: "Edit draft",
  },
  {
    id: uuid(),
    title: "removeDraft",
    label: "Remove draft",
  },
];

export const completedOptionsList = [
  {
    id: uuid(),
    title: "reusePosting",
    label: "Reuse posting",
  },
  {
    id: uuid(),
    title: "ViewJobPosting",
    label: "View job posting",
  },
];

export const pendingOptionsList = [
  {
    id: uuid(),
    title: "viewProposals",
    label: "View proposals",
  },
  {
    id: uuid(),
    title: "inviteFreelancer",
    label: "Invite freelancer",
  },
  {
    id: uuid(),
    title: "ViewJobPosting",
    label: "View job posting",
  },
  {
    id: uuid(),
    title: "editPosting",
    label: "Edit posting",
  },
  {
    id: uuid(),
    title: "reusePosting",
    label: "Reuse posting",
  },
  {
    id: uuid(),
    title: "removeDraft",
    label: "Remove posting",
  },
];

export const activeOptionsList = [
  {
    id: uuid(),
    title: "viewProposals",
    label: "View proposals",
  },
  {
    id: uuid(),
    title: "completeJob",
    label: "Complete Job",
  },
];

export const expiredOptionsList = [
  {
    id: uuid(),
    title: "reusePosting",
    label: "Reuse posting",
  },
  {
    id: uuid(),
    title: "removeDraft",
    label: "Remove posting",
  },
];
